{
  "schema_version": "1.5.0",
  "id": "CVE-2019-5010",
  "modified": "2022-04-19T17:32:41",
  "published": "2019-10-31T20:05:57",
  "details": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability.",
  "affected": [
    {
      "package": {
        "ecosystem": "generic",
        "name": "Python",
        "purl": "pkg:generic/python"
      },
      "ranges": []
    }
  ],
  "references": [],
  "database_specific": {
    "cwe_ids": []
  }
}